[project]
name = "flux"
version = "0.1.0"
description = "flux - an offline file converter tool"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyinstaller>=6.22.3",
    "pywebview>=6.2.1",
    "requests>=2.34.2",
]

[project.scripts]
flux = "flux.main:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
